# -*- coding: utf-8 -*-
"""Projek UAS - Sort Algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qjBoZhVOh3xU380JYlQkWWe7cNo7VmEl
"""

# Nurul Aliyah Dyah Sakhinah - F55121069

#Import Library
import time
import textwrap

#Untuk Wrap Array
def display_array(arr):
    wrapped_lines = textwrap.wrap(str(arr), width=80)
    for line in wrapped_lines:
        print(line)

# Function Bubble Sort
def bubble(arr):
    n = len(arr)

    # Untuk mulai mencatat waktu komputasi sort
    start_time = time.time()

    # Untuk Melakukan Bubble Sort
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]

        # Untuk Menampilkan 5 Iterasi Pertama dan 5 Iterasi Terakhir
        if i < 5 or i >= n-5:
            print(f"Iterasi Ke-{i+1}: {arr}")
            print("\n")

    # Untuk berhenti mencatat waktu komputasi dan menghitung selisihnya
    end_time = time.time()
    execution_time = end_time - start_time
    return arr, execution_time

# Function Insertion Sort
def insertion(arr):
    n = len(arr)

    # Untuk mulai mencatat waktu komputasi sort
    start_time = time.time()

    # Untuk Melakukan Insertion Sort
    for i in range(1, n):
        key = arr[i]
        j = i-1
        while j >= 0 and arr[j] > key:
            arr[j+1] = arr[j]
            j -= 1
        arr[j+1] = key

        # Untuk Menampilkan 5 Iterasi Pertama dan 5 Iterasi Terakhir
        if i <= 5 or i >= n-5:
            print(f"Iterasi Ke-{i}: {arr}")
            print("\n")

    # Untuk berhenti mencatat waktu komputasi dan menghitung selisihnya
    end_time = time.time()
    execution_time = end_time - start_time
    return arr, execution_time

# Program Utama
def main():
    arr = [12, 99, 62, 15, 20, 95, 39, 48, 3, 24, 8, 43, 74, 19, 97, 33, 49, 68, 55, 33, 90, 90, 7, 26, 85, 46, 39, 40, 9, 36, 60, 64, 89, 31, 25, 71, 21, 23, 63, 84, 32, 5, 3, 44, 21, 10, 21, 17, 50, 2, 36, 53, 79, 54, 19, 88, 1, 32, 31, 15, 6, 3, 1, 40, 22, 43, 18, 1, 77, 9, 59, 40, 7, 41, 81]

    print("\t\tPROJEK UAS PAA II - NURUL ALIYAH DYAH SAKHINAH_F55121069")
    print("============================================================================================")
    print("Data yang akan di urutkan:\n")
    display_array(arr)
    print("============================================================================================")

    sort_again = True

    while sort_again:
        choice = input("Pilih Algoritma Pengurutan (1 = Bubble Sort, 2 = Insertion Sort): ")
        print("============================================================================================")

        if choice == '1':
            sorted_arr, execution_time = bubble(arr.copy())
            algorithm = "Bubble Sort"
        elif choice == '2':
            sorted_arr, execution_time = insertion(arr.copy())
            algorithm = "Insertion Sort"
        else:
            print("Pilihan Tidak Valid, Coba Lagi")
            continue

        print("\n============================================================================================")
        print("Setelah Proses Pengurutan:")
        display_array(sorted_arr)
        print("============================================================================================")

        print(f"\n{algorithm} membutuhkan {execution_time:.6f} detik untuk mengeksekusi array.")
        print("============================================================================================")

        repeat = input("\nApakah Anda Mau Melakukan Pengurutan Lagi? (y/n): ")
        print("============================================================================================")
        if repeat.lower() != 'y':
            sort_again = False


if __name__ == "__main__":
    main()